#!/bin/sh
set -e
if [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
fi
if [ "$1" = purge ]; then
    getent passwd prime-lc-lcd >/dev/null && userdel prime-lc-lcd || true
    getent group prime-lc-lcd >/dev/null && groupdel prime-lc-lcd || true
fi
